import "./FriendsOnline.css";

const FriendsOnline = () => {

  return (
    <div className="friends-online-display">
      Imagine having friends, because I can't....😓
      <br />
      <br />
      <p style={{fontSize: '32px'}}>
        Is there a character that could even possibly EVEN TOUCH Madara Uchiha? Let alone defeat him. And I'm not talking about Edo Tensei Uchiha Madara. I'm not talking about Gedou Rinne Tensei Uchiha Madara either. Hell, I'm not even talking about Juubi Jinchuuriki Gedou Rinne Tensei Uchiha Madara with the Eternal Mangekyou Sharingan and Rinnegan doujutsus (with the rikodou abilities and being capable of both Amateratsu and Tsukuyomi genjutsu), equipped with his Gunbai, a perfect Susano'o, control of the juubi and Gedou Mazou, with Hashirama Senju's DNA implanted in him so he has mokuton kekkei genkai and can perform yin yang release ninjutsu while being an expert in kenjutsu and taijutsu.
        I’m also not talking about Kono Yo no Kyūseishu Futarime no Rikudō Juubi Jinchuuriki Gedou Rinne Tensei Uchiha Madara with the Eternal Mangekyou Sharingan (which is capable of Enton Amaterasu, Izanagi, Izanami and the Tsyukuyomi Genjutsu), his two original Rinnegan (which grant him Chikushōdō, Shuradō, Tendō, Ningendō, Jigokudō, Gakidō, Gedō, Banshō Ten’in, Chibaku Tensei, Shinra Tensei, Tengai Shinsei and Banbutsu Sōzō) and a third Tomoe Rinnegan on his forehead, capable of using Katon, Fūton, Raiton, Doton, Suiton, Mokuton, Ranton, Inton, Yōton and even Onmyōton Jutsu, equipped with his Gunbai(capable of using Uchihagaeshi) and a Shakujō because he is a master in kenjutsu and taijutsu, a perfect Susano’o (that can use Yasaka no Magatama ), control of both the Juubi and the Gedou Mazou, with Hashirama Senju’s DNA and face implanted on his chest, his four Rinbo Hengoku Clones guarding him and nine Gudōdama floating behind him AFTER he absorbed Senjutsu from the First Hokage, entered Rikudō Senjutsu Mode, cast Mugen Tsukuyomi on everybody and used Shin: Jukai Kōtan so he can use their Chakra while they are under Genjutsu. I'm definitely NOT Talking about sagemode sage of the six paths Juubi Jinchuuriki Gedou Rinne Tensei Super Saiyan 4 Uchiha Madara with the Eternal Mangekyou Sharingan, Rinnegan, Mystic Eyes of Death Perception, and Geass doujutsus, equipped with Shining Trapezohedron while casting Super Tengen Toppa Gurren Lagann as his Susanoo, controlling the Gold Experience Requiem stand, having become the original vampire after Alucard, able to tap into the speedforce, wearing the Kamen Rider Black RX suit and Gedou Mazou, with Hashirama Senju's DNA implanted in him so he has mokuton kekkei genkai and can perform yin yang release ninjutsu while being an expert in kenjutsu and taijutsu and having eaten Popeye's spinach. I'm talking about sagemode sage of the six paths Juubi Jinchuuriki Gedou Rinne Tensei Legendary Super Saiyan 4 Uchiha Madara with the Eternal Mangekyou Sharingan, Rinnegan, Mystic Eyes of Death Perception, and Geass doujutsus, equipped with his Shining Trapezohedron while casting Super Tengen Toppa Gurren Lagann as his Susanoo, controlling the Gold Experience Requiem stand, having become the original vampire after having absorbed Alucard as well as a God Hand, able to tap into the speedforce, wearing the Kamen Rider Black RX suit, with Kryptonian DNA implanted in him and having eaten Popeye's spinach while possessing quantum powers like Dr. Manhattan and having mastered Hokuto Shinken.
      </p>
    </div>
  )
}

export default FriendsOnline;